use_frameworks!

platform :ios, '9.0'

target 'JKNoticationHelper_Swift_Example' do
  pod 'JKNoticationHelper_Swift', :path => '../../'

  target 'JKNoticationHelper_Swift_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 8.0.7'
  end
end
