use_frameworks!

platform :ios, '8.0'

target 'JKNoticationHelper_Example' do
  pod 'JKNoticationHelper', :path => '../../'

  target 'JKNoticationHelper_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
